name: Main CI

on: push

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.32.3-focal
    steps:
      - uses: actions/checkout@v3
      - name: Add trusted certificate
        run: |
          cp ca.pem /usr/share/ca-certificates/kassette.crt
          echo kassette.crt >> /etc/ca-certificates.conf
          update-ca-certificates
          apt update && apt install libnss3-tools
          mkdir -p /root/.pki/nssdb
          certutil -d sql:/root/.pki/nssdb -A -t "C,," -n kassette -i ca.pem
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Setup
        run: npm ci
      - name: Test
        run: HOME=/root npm run test
      - name: Test with proxy
        run: HOME=/root npm run test:proxy
      - uses: actions/upload-artifact@v3
        with:
          name: test-ubuntu
          path: test-results
        if: failure()
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add trusted certificate
        run: certutil -addstore -f "ROOT" ca.pem
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Setup
        run: npm ci
      - name: Install playwright
        run: npx playwright install --with-deps chromium webkit firefox
      - name: Test
        run: npm run test
      - name: Test with proxy
        run: npm run test:proxy
      - uses: actions/upload-artifact@v3
        with:
          name: test-windows
          path: test-results
        if: failure()
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add trusted certificate
        run: |
          sudo security authorizationdb write com.apple.trust-settings.admin allow
          sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ca.pem
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Setup
        run: npm ci
      - name: Install playwright
        run: npx playwright install --with-deps chromium webkit firefox
      - name: Test
        run: npm run test
      - name: Test with proxy
        run: npm run test:proxy
      - uses: actions/upload-artifact@v3
        with:
          name: test-macos
          path: test-results
        if: failure()
